# Bỏ version để tránh warning trong Docker Compose mới
services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongP@ssw0rd123
    volumes:
      - sql_data:/var/opt/mssql
    restart: always
    networks:
      - monitoring
      
  web-app:
    # SỬA: Đổi image name để khớp với Jenkinsfile
    image: tvloc02/web-sellbook:1.0.3  # Thay vì tvloc02/web-app:1.0.3
    container_name: web-app
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=quanlynhansu;User Id=sa;Password=StrongP@ssw0rd123;
    depends_on:
      - sqlserver
    restart: unless-stopped  # Thêm restart policy
    networks:
      - monitoring
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    ports:
      - "9090:9090"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=5d
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    networks:
      - monitoring
      
  grafana:
    image: grafana/grafana:latest  # Thêm tag latest để rõ ràng
    container_name: monitoring-grafana
    user: root
    ports:
      - "3000:3000"
    environment:
      # Thêm biến môi trường mặc định
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus  # Thêm dependency
    networks:
      - monitoring

volumes:
  sql_data:
  prometheus-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge
